language: c
os:
  - linux
  # (osx and freebsd suffer from openssl incompatibilities)
dist: xenial

# try to build
script: ./configure --enable-silent-rules --enable-debug && make && make check

compiler:
  - clang
  - gcc
