name: cooljeanius/trousers-0.3.11.2
on:
  push:
    branches:
    - "**/*"
  pull_request:
jobs:
  test:
    runs-on: ubuntu-16.04
    steps:
    - name: checkout
      uses: actions/checkout@v3.5.0
#     # 'Transformers::TravisCI::Scripts::Dependencies' dependencies are currently unsupported
#     # 'compiler' was not transformed because there is no suitable equivalent in GitHub Actions
    - run: "./configure --enable-silent-rules --enable-debug && make && make check"
    strategy:
      matrix:
        compiler:
        - clang
        - gcc
