name: cooljeanius/trousers-0.3.11.2
on:
  push:
    branches:
    - "**/*"
  pull_request:
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - name: checkout
      uses: actions/checkout@v3.5.0
#     # 'Transformers::TravisCI::Scripts::Dependencies' dependencies are currently unsupported
#     # 'compiler' was not transformed because there is no suitable equivalent in GitHub Actions
    - run: sudo apt-get install -y openssl
    - run: "./configure --enable-silent-rules --enable-debug CC=${{ matrix.compiler }} && make && make check"
    strategy:
      fail-fast: false
      matrix:
        compiler:
        - clang
        - gcc
