name: cooljeanius/trousers-0.3.11.2
on:
  push:
    branches:
    - "**/*"
  pull_request:
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - name: checkout
      uses: actions/checkout@v3.5.0
#     # 'Transformers::TravisCI::Scripts::Dependencies' dependencies are currently unsupported
#     # 'compiler' was not transformed because there is no suitable equivalent in GitHub Actions
    - run: sudo apt-get install -y openssl libssl-dev ssl-cert exuberant-ctags universal-ctags id-utils gettext global
    - run: "./configure --enable-silent-rules --enable-debug CC=${{ matrix.compiler }}"
    - run: "make || stat -t Makefile"
    - run: "make check || (make ID && make TAGS && make CTAGS && make GTAGS)"
      if: success()
    strategy:
      fail-fast: false
      matrix:
        compiler:
        - clang
        - gcc
